### ISSUE TITLE
STL files are missing the Right Lower XY Carriage Mount

### ISSUE THREAD

**Issue by TheeDynamikOne** [celer/FT5_CoreXY_EVA#2]
Hello Celer,

I'm working on this conversion, using the carbon tube. I noticed in the STL files the Right XY carriage mount lower cf & al files are missing. It looks like all the other STL files are present.

I attempted to pull the carriage mount file from OpenSCAD but I'm used to GUI based CAD programs and I'm failing miserably with OpenSCAD on Windows.

Thank you for your time and contribution to the good ol' Folder Tech community. I've had my FT-5 since 2017 and I've invested too much time with upgrades but its always been fun. I have a Duet board, 0.9° steppers, 500w power supply, etc. I really enjoy these printers and they print really well when dialed in.

**Comment by TheeDynamikOne** [comment]
Do you think I need a Linux environment to utilize these files with OpenSCAD properly?  

When I try to use the make the file, I'm using the command prompt but I'm having issues with windows finding the proper directory to execute the make command.

When I try to open the FT-5 model in OpenSCAD I can open the model and manipulate the Customizer successfully, but I can't get OpenScad to export individual parts. I can render the entire printer but it renders it mainly as one piece so I can't get the individual parts out of it.

I have very little coding experience so I could be missing something obvious. I'm trying to work with ChatGPT to trouble shoot the errors I'm receiving in OpenScad but I keep going in circles.

**Comment by celer** [comment]
Sorry I forgot to add those. It's a bit convoluted to get it to generate the parts required. 

The missing parts should be there now.
